import {defineType, defineField} from 'sanity'

const pageHeroFields = [
  defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
  defineField({name: 'heroTitle', title: 'Hero title', type: 'string'}),
  defineField({name: 'heroDescription', title: 'Hero description', type: 'text', rows: 3}),
  defineField({name: 'heroImage', title: 'Hero image', type: 'mediaImage'}),
  defineField({name: 'seoTitle', title: 'SEO title', type: 'string'}),
  defineField({name: 'metaDescription', title: 'Meta description', type: 'text', rows: 2}),
]

export const homePageType = defineType({
  name: 'homePage',
  title: 'Home Page',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'sections', title: 'Sections'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', initialValue: 'Home Page', group: 'hero'}),
    ...pageHeroFields.map((field) => ({...field, group: field.name.startsWith('seo') || field.name === 'metaDescription' ? 'seo' : 'hero'})),
    defineField({name: 'heroVideoUrl', title: 'Hero video URL', type: 'string', group: 'hero'}),
    defineField({name: 'featuredTreatments', title: 'Featured treatments', type: 'array', of: [{type: 'reference', to: [{type: 'treatment'}]}], group: 'sections'}),
    defineField({name: 'categorySectionEyebrow', title: 'Category section eyebrow', type: 'string', group: 'sections'}),
    defineField({name: 'categorySectionTitle', title: 'Category section title', type: 'string', group: 'sections'}),
    defineField({name: 'categorySectionText', title: 'Category section text', type: 'text', rows: 2, group: 'sections'}),
    defineField({name: 'featuredSectionEyebrow', title: 'Featured section eyebrow', type: 'string', group: 'sections'}),
    defineField({name: 'featuredSectionTitle', title: 'Featured section title', type: 'string', group: 'sections'}),
    defineField({name: 'featuredSectionLink', title: 'Featured section link', type: 'link', group: 'sections'}),
    defineField({name: 'trustItems', title: 'Trust bar items', type: 'array', of: [{type: 'iconText'}], group: 'sections'}),
    defineField({name: 'whyChooseUs', title: 'Why choose us', type: 'array', of: [{type: 'iconText'}], group: 'sections'}),
    defineField({name: 'whyChooseEyebrow', title: 'Why choose eyebrow', type: 'string', group: 'sections'}),
    defineField({name: 'whyChooseTitle', title: 'Why choose title', type: 'string', group: 'sections'}),
    defineField({name: 'doctor', title: 'Doctor section', type: 'reference', to: [{type: 'doctor'}], group: 'sections'}),
    defineField({name: 'doctorEyebrow', title: 'Doctor eyebrow', type: 'string', group: 'sections'}),
    defineField({name: 'testimonials', title: 'Testimonials', type: 'array', of: [{type: 'reference', to: [{type: 'testimonial'}]}], group: 'sections'}),
    defineField({name: 'testimonialEyebrow', title: 'Testimonials eyebrow', type: 'string', group: 'sections'}),
    defineField({name: 'testimonialTitle', title: 'Testimonials title', type: 'string', group: 'sections'}),
    defineField({name: 'realResults', title: 'Real results', type: 'array', of: [{type: 'reference', to: [{type: 'beforeAfter'}]}], group: 'sections'}),
    defineField({name: 'faqs', title: 'FAQs', type: 'array', of: [{type: 'qa'}], group: 'sections'}),
    defineField({name: 'ctaTitle', title: 'CTA title', type: 'string', group: 'sections'}),
    defineField({name: 'ctaText', title: 'CTA text', type: 'text', rows: 2, group: 'sections'}),
    defineField({name: 'ctaEyebrow', title: 'CTA eyebrow', type: 'string', group: 'sections'}),
    defineField({name: 'ctaBullets', title: 'CTA bullets', type: 'array', of: [{type: 'string'}], group: 'sections'}),
    defineField({name: 'banners', title: 'Promotional banners', type: 'array', of: [{type: 'iconText'}], group: 'sections'}),
    defineField({name: 'statistics', title: 'Statistics / counters', type: 'array', of: [{type: 'keyFact'}], group: 'sections'}),
    defineField({name: 'seo', title: 'Full SEO', type: 'seoFields', group: 'seo'}),
  ],
  preview: {prepare: () => ({title: 'Home Page'})},
})

export const aboutPageType = defineType({
  name: 'aboutPage',
  title: 'About Page',
  type: 'document',
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', initialValue: 'About Page'}),
    ...pageHeroFields,
    defineField({name: 'storyEyebrow', title: 'Story eyebrow', type: 'string'}),
    defineField({name: 'storyTitle', title: 'Story title', type: 'string'}),
    defineField({name: 'storyBody', title: 'Story paragraphs', type: 'array', of: [{type: 'text'}]}),
    defineField({name: 'mission', title: 'Mission', type: 'text', rows: 3}),
    defineField({name: 'vision', title: 'Vision', type: 'text', rows: 3}),
    defineField({name: 'timeline', title: 'Timeline', type: 'array', of: [{type: 'keyFact'}]}),
    defineField({name: 'clinicHighlights', title: 'Clinic highlights', type: 'array', of: [{type: 'iconText'}]}),
    defineField({name: 'statistics', title: 'Statistics / counters', type: 'array', of: [{type: 'keyFact'}]}),
    defineField({name: 'gallery', title: 'Gallery', type: 'array', of: [{type: 'mediaImage'}]}),
    defineField({name: 'galleryEyebrow', title: 'Gallery eyebrow', type: 'string'}),
    defineField({name: 'galleryTitle', title: 'Gallery title', type: 'string'}),
    defineField({name: 'galleryLinkText', title: 'Gallery link text', type: 'string'}),
    defineField({name: 'videoUrl', title: 'Video URL', type: 'url'}),
    defineField({name: 'testimonials', title: 'Testimonials', type: 'array', of: [{type: 'reference', to: [{type: 'testimonial'}]}]}),
    defineField({name: 'ctaTitle', title: 'CTA title', type: 'string'}),
    defineField({name: 'ctaText', title: 'CTA text', type: 'text', rows: 2}),
    defineField({name: 'ctaButtonText', title: 'CTA button text', type: 'string'}),
    defineField({name: 'seo', title: 'Full SEO', type: 'seoFields'}),
  ],
  preview: {prepare: () => ({title: 'About Page'})},
})

export const contactPageType = defineType({
  name: 'contactPage',
  title: 'Contact Page',
  type: 'document',
  fields: [
    defineField({name: 'title', title: 'Title', type: 'string', initialValue: 'Contact Page'}),
    ...pageHeroFields,
    defineField({name: 'email', title: 'Primary email', type: 'string'}),
    defineField({name: 'emergencyContact', title: 'Emergency contact', type: 'string'}),
    defineField({name: 'whatsappNumber', title: 'WhatsApp number', type: 'string'}),
    defineField({name: 'mapEmbed', title: 'Google map embed URL', type: 'url'}),
    defineField({name: 'mapTitle', title: 'Map title', type: 'string'}),
    defineField({name: 'mapsUrl', title: 'Google maps directions URL', type: 'url'}),
    defineField({name: 'directionsLabel', title: 'Directions link label', type: 'string'}),
    defineField({name: 'whatsappLabel', title: 'WhatsApp link label', type: 'string'}),
    defineField({name: 'openingHours', title: 'Opening hours', type: 'array', of: [{type: 'keyFact'}]}),
    defineField({name: 'contactCta', title: 'Contact CTA', type: 'link'}),
    defineField({name: 'clinicSectionTitle', title: 'Clinic section title', type: 'string'}),
    defineField({name: 'formEyebrow', title: 'Form eyebrow', type: 'string'}),
    defineField({name: 'formIntro', title: 'Form intro', type: 'text', rows: 2}),
    defineField({name: 'nameLabel', title: 'Name label', type: 'string'}),
    defineField({name: 'namePlaceholder', title: 'Name placeholder', type: 'string'}),
    defineField({name: 'phoneLabel', title: 'Phone label', type: 'string'}),
    defineField({name: 'phonePlaceholder', title: 'Phone placeholder', type: 'string'}),
    defineField({name: 'concernLabel', title: 'Concern label', type: 'string'}),
    defineField({name: 'concernPlaceholder', title: 'Concern placeholder', type: 'text', rows: 2}),
    defineField({name: 'submitLabel', title: 'Submit label', type: 'string'}),
    defineField({name: 'successMessage', title: 'Success message', type: 'string'}),
    defineField({name: 'errorMessage', title: 'Error message', type: 'string'}),
    defineField({name: 'nameError', title: 'Name required message', type: 'string'}),
    defineField({name: 'phoneError', title: 'Phone required message', type: 'string'}),
    defineField({name: 'phoneInvalidError', title: 'Phone invalid message', type: 'string'}),
    defineField({name: 'seo', title: 'Full SEO', type: 'seoFields'}),
  ],
  preview: {prepare: () => ({title: 'Contact Page'})},
})

export const footerSettingsType = defineType({
  name: 'footerSettings',
  title: 'Footer',
  type: 'document',
  fields: [
    defineField({name: 'brandText', title: 'Brand text', type: 'text', rows: 3}),
    defineField({name: 'quickLinks', title: 'Quick links', type: 'array', of: [{type: 'link'}]}),
    defineField({name: 'legalLinks', title: 'Legal / support links', type: 'array', of: [{type: 'link'}]}),
    defineField({name: 'newsletterTitle', title: 'Newsletter title', type: 'string'}),
    defineField({name: 'newsletterText', title: 'Newsletter text', type: 'text', rows: 2}),
    defineField({name: 'newsletterPlaceholder', title: 'Newsletter placeholder', type: 'string'}),
    defineField({name: 'newsletterButtonText', title: 'Newsletter button text', type: 'string'}),
    defineField({name: 'newsletterSuccess', title: 'Newsletter success message', type: 'string'}),
    defineField({name: 'newsletterError', title: 'Newsletter error message', type: 'string'}),
    defineField({name: 'mapLinkText', title: 'Map link text', type: 'string'}),
    defineField({name: 'parentBrandText', title: 'Parent brand text', type: 'string'}),
    defineField({name: 'copyrightText', title: 'Copyright text', type: 'string'}),
  ],
  preview: {prepare: () => ({title: 'Footer'})},
})

export const seoSettingsType = defineType({
  name: 'seoSettings',
  title: 'Global SEO Settings',
  type: 'document',
  fields: [
    defineField({name: 'siteTitle', title: 'Site title', type: 'string'}),
    defineField({name: 'defaultDescription', title: 'Default meta description', type: 'text', rows: 2}),
    defineField({name: 'defaultKeywords', title: 'Default keywords', type: 'array', of: [{type: 'string'}], options: {layout: 'tags'}}),
    defineField({name: 'defaultOpenGraphImage', title: 'Default Open Graph image', type: 'mediaImage'}),
    defineField({name: 'twitterCard', title: 'Twitter card', type: 'string'}),
    defineField({name: 'robots', title: 'Robots settings', type: 'string'}),
    defineField({name: 'canonicalUrl', title: 'Canonical URL', type: 'url'}),
    defineField({name: 'favicon', title: 'Favicon', type: 'mediaImage'}),
    defineField({name: 'appleTouchIcon', title: 'Apple touch icon', type: 'mediaImage'}),
    defineField({name: 'themeColor', title: 'Theme color', type: 'string'}),
    defineField({name: 'manifest', title: 'Manifest JSON', type: 'text', rows: 6}),
    defineField({name: 'structuredData', title: 'Structured data JSON', type: 'text', rows: 6}),
    defineField({name: 'blogEyebrow', title: 'Blog index eyebrow', type: 'string'}),
    defineField({name: 'blogTitle', title: 'Blog index title', type: 'string'}),
    defineField({name: 'blogDescription', title: 'Blog index description', type: 'text', rows: 2}),
    defineField({name: 'blogEmptyText', title: 'Blog empty state text', type: 'string'}),
    defineField({name: 'doctorsEyebrow', title: 'Doctors index eyebrow', type: 'string'}),
    defineField({name: 'doctorsTitle', title: 'Doctors index title', type: 'string'}),
    defineField({name: 'doctorsDescription', title: 'Doctors index description', type: 'text', rows: 2}),
    defineField({name: 'medicalDisclaimerLabel', title: 'Medical disclaimer label', type: 'string'}),
    defineField({name: 'medicalDisclaimer', title: 'Medical disclaimer text', type: 'text', rows: 3}),
    defineField({name: 'faqEyebrow', title: 'FAQ page eyebrow', type: 'string'}),
    defineField({name: 'faqTitle', title: 'FAQ page title', type: 'string'}),
    defineField({name: 'faqDescription', title: 'FAQ page description', type: 'text', rows: 2}),
    defineField({name: 'offersEyebrow', title: 'Offers page eyebrow', type: 'string'}),
    defineField({name: 'offersTitle', title: 'Offers page title', type: 'string'}),
    defineField({name: 'offersDescription', title: 'Offers page description', type: 'text', rows: 2}),
    defineField({name: 'offerCardLabel', title: 'Offer card label', type: 'string'}),
    defineField({name: 'offerButtonText', title: 'Offer button text', type: 'string'}),
  ],
  preview: {prepare: () => ({title: 'Global SEO Settings'})},
})

export const navigationSettingsType = defineType({
  name: 'navigationSettings',
  title: 'Navigation',
  type: 'document',
  fields: [
    defineField({
      name: 'items',
      title: 'Menu items',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            defineField({name: 'label', title: 'Label', type: 'string'}),
            defineField({name: 'href', title: 'Internal / external link', type: 'string'}),
            defineField({name: 'order', title: 'Order', type: 'number'}),
            defineField({name: 'visible', title: 'Visible', type: 'boolean', initialValue: true}),
            defineField({name: 'dropdownCategory', title: 'Dropdown category', type: 'reference', to: [{type: 'category'}]}),
          ],
          preview: {select: {title: 'label', subtitle: 'href'}},
        },
      ],
    }),
  ],
  preview: {prepare: () => ({title: 'Navigation'})},
})
