import {defineType, defineField} from 'sanity'

export const treatmentType = defineType({
  name: 'treatment',
  title: 'Treatment',
  type: 'document',
  groups: [
    {name: 'main', title: 'Main', default: true},
    {name: 'hero', title: 'Hero'},
    {name: 'content', title: 'Content'},
    {name: 'cost', title: 'Cost'},
    {name: 'process', title: 'Process & FAQ'},
    {name: 'relations', title: 'Relations'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'title', title: 'Name', type: 'string', group: 'main', validation: (r) => r.required()}),
    defineField({name: 'slug', title: 'Slug', type: 'slug', options: {source: 'title'}, group: 'main', validation: (r) => r.required()}),
    defineField({name: 'category', title: 'Category', type: 'reference', to: [{type: 'category'}], group: 'main'}),
    defineField({name: 'short', title: 'Short description', type: 'text', rows: 2, group: 'main'}),
    defineField({name: 'status', title: 'Status', type: 'string', options: {list: ['published', 'draft'], layout: 'radio'}, initialValue: 'published', group: 'main'}),
    defineField({name: 'image', title: 'Image', type: 'mediaImage', group: 'main', validation: (r) => r.required()}),
    defineField({name: 'heroTitle', title: 'Hero title', type: 'string', group: 'hero'}),
    defineField({name: 'pageTitle', title: 'Page H1', type: 'string', group: 'hero'}),
    defineField({name: 'hero', title: 'Hero subtitle', type: 'text', rows: 2, group: 'hero'}),
    defineField({name: 'description', title: 'Hero description', type: 'text', rows: 3, group: 'hero'}),
    defineField({name: 'ctaText', title: 'CTA button text', type: 'string', group: 'hero'}),
    defineField({name: 'ctaLink', title: 'CTA button link', type: 'string', group: 'hero'}),
    defineField({name: 'featured', title: 'Featured (signature)', type: 'boolean', initialValue: false, group: 'main'}),
    defineField({name: 'order', title: 'Order', type: 'number', initialValue: 0, group: 'main'}),
    defineField({name: 'overviewHeading', title: 'Overview heading', type: 'string', group: 'content'}),
    defineField({name: 'whatHeading', title: 'What section label', type: 'string', group: 'content'}),
    defineField({name: 'what', title: 'What is it', type: 'text', rows: 4, group: 'content'}),
    defineField({name: 'quickInfo', title: 'Quick information', type: 'quickInfo', group: 'content'}),
    defineField({name: 'idealCandidateHeading', title: 'Ideal candidate heading', type: 'string', group: 'content'}),
    defineField({name: 'whoFor', title: "Who it's for", type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'symptoms', title: 'Symptoms', type: 'array', of: [{type: 'iconText'}], group: 'content'}),
    defineField({name: 'benefits', title: 'Benefits', type: 'array', of: [{type: 'benefitItem'}], group: 'content'}),
    defineField({name: 'duration', title: 'Duration', type: 'string', group: 'content'}),
    defineField({name: 'sessions', title: 'Sessions', type: 'string', group: 'content'}),
    defineField({name: 'downtime', title: 'Downtime notes', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'costHeading', title: 'Cost section heading', type: 'string', group: 'cost'}),
    defineField({name: 'costDescription', title: 'Cost section details', type: 'text', rows: 3, group: 'cost'}),
    defineField({name: 'priceFrom', title: 'Starting price', type: 'string', group: 'cost'}),
    defineField({name: 'pricing', title: 'Cost items', type: 'array', of: [{type: 'costItem'}], group: 'cost'}),
    defineField({name: 'procedureHeading', title: 'Procedure section label', type: 'string', group: 'process'}),
    defineField({name: 'processHeading', title: 'Procedure section heading', type: 'string', group: 'process'}),
    defineField({name: 'howItWorks', title: 'How it works (steps)', type: 'array', of: [{type: 'step'}], group: 'process'}),
    defineField({name: 'benefitsHeading', title: 'Benefits heading', type: 'string', group: 'content'}),
    defineField({name: 'resultsHeading', title: 'Before/after heading', type: 'string', group: 'relations'}),
    defineField({name: 'whyChooseHeading', title: 'Why choose heading', type: 'string', group: 'content'}),
    defineField({name: 'whyChooseDescription', title: 'Why choose details', type: 'text', rows: 3, group: 'content'}),
    defineField({name: 'whyChooseItems', title: 'Why choose points', type: 'array', of: [{type: 'string'}], group: 'content'}),
    defineField({name: 'specialistHeading', title: 'Doctor/specialist heading', type: 'string', group: 'process'}),
    defineField({name: 'specialistDescription', title: 'Doctor/specialist details', type: 'text', rows: 3, group: 'process'}),
    defineField({name: 'specialistHighlights', title: 'Doctor/specialist points', type: 'array', of: [{type: 'string'}], group: 'process'}),
    defineField({name: 'doctorNote', title: "Doctor's note", type: 'text', rows: 3, group: 'process'}),
    defineField({name: 'faqHeading', title: 'FAQ heading', type: 'string', group: 'process'}),
    defineField({name: 'faqs', title: 'FAQs', type: 'array', of: [{type: 'qa'}], group: 'process'}),
    defineField({name: 'relatedTreatments', title: 'Related treatments', type: 'array', of: [{type: 'reference', to: [{type: 'treatment'}]}], group: 'relations'}),
    defineField({name: 'realResults', title: 'Before & after results', type: 'array', of: [{type: 'reference', to: [{type: 'beforeAfter'}]}], group: 'relations'}),
    defineField({name: 'seo', title: 'SEO', type: 'seoFields', group: 'seo'}),
  ],
  orderings: [{title: 'Manual order', name: 'order', by: [{field: 'order', direction: 'asc'}]}],
  preview: {select: {title: 'title', subtitle: 'short', media: 'image.asset'}},
})
